task:
  name: FreeBSD-$RELEASEVER-$CONFIG
  env:
    CIRRUS_OS: freebsd
    matrix:
      - CONFIG: minimal
      - CONFIG: full
    matrix:
      - RELEASEVER: 12-1
  freebsd_instance:
    image_family: freebsd-$RELEASEVER
  install_bash_script: pkg install -y bash
  install_build_depends_script: bash ./autotest/ci/install-build-depends.sh
  build_and_test_script: bash ./autotest/ci/build-and-test.sh

task:
  env:
    matrix:
      - RELEASEVER: 7
      - RELEASEVER: 8
    matrix:
      - CONFIG: minimal
      - CONFIG: full
      - CONFIG: rpm
  name: CentOS-$RELEASEVER-$CONFIG
  container:
    image: centos:$RELEASEVER
  install_build_depends_script: bash ./autotest/ci/install-build-depends.sh
  build_and_test_script: bash ./autotest/ci/build-and-test.sh

task:
  env:
    # Git bash
    CIRRUS_SHELL: "C:\\Program Files\\Git\\bin\\bash.exe"
    CONFIG: minimal
  name: Windows-minimal
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  vcpkg_cache:
    folder: "C:\\Users\\ContainerAdministrator\\vcpkg-minimal"
    fingerprint_script:
      - echo "OS: ${CIRRUS_OS}"
      - echo "TAG: ${CIRRUS_TAG}"
      - echo "BRANCH: ${CIRRUS_BRANCH}"
      - echo "PR: ${CIRRUS_PR}"
      - cat autotest/ci/install-build-depends.sh
    reupload_on_changes: true
  environment_script: env
  install_build_depends_script: ./autotest/ci/install-build-depends.sh
  build_and_test_script: ./autotest/ci/build-and-test.sh
