task:
  name: FreeBSD-${RELEASEVER}-${CONFIG}
  env:
    CIRRUS_OS: freebsd
    RELEASEVER: 12-1
    matrix:
      - CONFIG: minimal
      - CONFIG: full
  freebsd_instance:
    image_family: freebsd-${RELEASEVER}
  install_bash_script: pkg install -y bash
  <<: &scripts
    environment_script: bash ./tests/ci/print-env.sh
    install_build_depends_script: bash ./tests/ci/install-build-depends.sh
    build_and_test_script: bash ./tests/ci/build-and-test.sh

task:
  name: CentOS-${RELEASEVER}-${CONFIG}-${CC}
  env:
    matrix:
      - RELEASEVER: 7
        CC: gcc
      - RELEASEVER: 8
        CC: gcc
      - RELEASEVER: 8
        CC: clang
    matrix:
      - CONFIG: minimal
      - CONFIG: full
      - CONFIG: rpm
  container:
    image: centos:${RELEASEVER}
  <<: *scripts

task:
  name: Mac-OSX-${CONFIG}
  env:
    matrix:
      - CONFIG: minimal
      - CONFIG: full
  osx_instance:
    image: catalina-xcode
  <<: *scripts

task:
  name: Windows-${CONFIG}-${ARCH}
  env:
    # Git bash
    CIRRUS_SHELL: "C:\\Program Files\\Git\\bin\\bash.exe"
    # Cirrus gets upset when you have more than 2 windows builds
    matrix:
      - CONFIG: minimal
        ARCH: x86
      - CONFIG: full
        ARCH: x64
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  vcpkg_cache:
    # For some reason, $HOME is weird here
    folder: "C:\\Users\\ContainerAdministrator\\vcpkg-cache-${CONFIG}-${ARCH}"
    fingerprint_script:
      - echo "CONFIG: ${CONFIG}"
      - echo "ARCH: ${ARCH}"
    reupload_on_changes: true
  <<: *scripts

# vi: syn=yaml et ts=2 sw=2 :
