task:
  name: FreeBSD-$RELEASEVER-$CONFIG
  env:
    CIRRUS_OS: freebsd
    matrix:
      - CONFIG: minimal
      - CONFIG: full
    matrix:
      - RELEASEVER: 12-1
      - RELEASEVER: 11-3-snap
  freebsd_instance:
    image_family: freebsd-$RELEASEVER
  install_bash_script: pkg install -y bash
  install_build_depends_script: bash ./autotest/ci/install-build-depends.sh
  build_and_test_script: bash ./autotest/ci/build-and-test.sh

task:
  env:
    matrix:
      - RELEASEVER: 7
      - RELEASEVER: 8
    matrix:
      - CONFIG: minimal
      - CONFIG: full
  name: CentOS-$RELEASEVER-$CONFIG
  container:
    image: centos:$RELEASEVER
  install_build_depends_script: bash ./autotest/ci/install-build-depends.sh
  build_and_test_script: bash ./autotest/ci/build-and-test.sh
