task:
  name: FreeBSD-$RELEASEVER-$CONFIG
  env:
    CIRRUS_OS: freebsd
    matrix:
      - CONFIG: minimal
      - CONFIG: full
    matrix:
      - RELEASEVER: 12-1
  freebsd_instance:
    image_family: freebsd-$RELEASEVER
  install_bash_script: pkg install -y bash
  install_build_depends_script: bash ./tests/ci/install-build-depends.sh
  build_and_test_script: bash ./tests/ci/build-and-test.sh

task:
  env:
    matrix:
      - RELEASEVER: 7
        CC: gcc
      - RELEASEVER: 8
        CC: gcc
      - RELEASEVER: 8
        CC: clang
    matrix:
      - CONFIG: minimal
      - CONFIG: full
      - CONFIG: rpm
  name: CentOS-$RELEASEVER-$CONFIG-$CC
  container:
    image: centos:$RELEASEVER
  install_build_depends_script: bash ./tests/ci/install-build-depends.sh
  build_and_test_script: bash ./tests/ci/build-and-test.sh

task:
  env:
    # Git bash
    CIRRUS_SHELL: "C:\\Program Files\\Git\\bin\\bash.exe"
    # Cirrus gets upset when you have more than 2 windows builds
    matrix:
      - CONFIG: minimal
        ARCH: x86
      - CONFIG: full
        ARCH: x64
  name: Windows-${CONFIG}-${ARCH}
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  vcpkg_cache:
    # For some reason, $HOME is weird here
    folder: "C:\\Users\\ContainerAdministrator\\vcpkg-${CONFIG}-${ARCH}"
    fingerprint_script:
      - echo "OS: ${CIRRUS_OS}"
      - echo "CONFIG: ${CONFIG}"
      - echo "ARCH: ${ARCH}"
      - echo "PR: ${CIRRUS_PR}"
      - md5sum tests/ci/install-build-depends.sh
    reupload_on_changes: true
  environment_script: env
  install_build_depends_script: ./tests/ci/install-build-depends.sh
  build_and_test_script: ./tests/ci/build-and-test.sh

# vi: syn=yaml et ts=2 sw=2 :
