language: c
os: linux
dist: bionic
arch: amd64
compiler:
  - gcc
  - clang
env:
  - CONFIG=minimal
  - CONFIG=full

jobs:
  allow_failures:
#   - os: windows
#     env: CONFIG=full

  # Additional builds to do (outside the build matrix)
  include:
    # SSL builds are currently broken on openssl < 1.1 (xenial has 1.0.2),
    # so only build the minimal config
    - os: linux
      dist: xenial
      arch: amd64
      env: CONFIG=minimal OLD=1
    # ARM builds
    - os: linux
      arch: arm64
      env: CONFIG=full
    - os: linux
      arch: arm64
      env: CONFIG=minimal
    # Debian package builds
    - os: linux
      arch: amd64
      env: CONFIG=deb
    # Docker build
    - language: minimal
      os: linux
      arch: amd64
      services: docker
      env: CONFIG=docker
    # Mac OS X builds
    - os: osx
      env: CONFIG=full
    - os: osx
      env: CONFIG=minimal

addons:
  homebrew:
    packages:
    - cmake
    - openssl
    - sqlite

install:
  - autotest/travis/install-build-depends.sh
script:
  - autotest/travis/build-and-test.sh

