language: c
os: linux
dist: xenial
arch: amd64
compiler:
  - gcc
  - clang
env:
  - CONFIG=minimal
  - CONFIG=full

jobs:
  allow_failures:
#   - os: windows
#     env: CONFIG=full

  # Additional builds to do (outside the build matrix)
  include:
    # Bionic builds
    - name: bionic full
      dist: bionic
      env: CONFIG=full
    - name: bionic minimal
      dist: bionic
      env: CONFIG=minimal
    # ARM builds
    - name: arm64 full
      arch: arm64
      env: CONFIG=full
    - name: arm64 minimal
      arch: arm64
      env: CONFIG=minimal
    # Debian package builds
    - name: debian package
      env: CONFIG=deb
    - name: bionic debian package
      dist: bionic
      env: CONFIG=deb
    # Docker build
    - name: docker
      language: minimal
      services: docker
      env: CONFIG=docker
    # Mac OS X builds
    - name: Mac OSX full
      os: osx
      env: CONFIG=full
    - name: Mac OSX minimal
      os: osx
      env: CONFIG=minimal
    # Windows builds
#   - name: Windows full
#     os: windows
#     env: CONFIG=full
#     cache:
#       directories:
#         - $HOME/vcpkg-full
    - name: Windows minimal
      os: windows
      env: CONFIG=minimal
      cache:
        directories:
          - $HOME/vcpkg-minimal

addons:
  homebrew:
    packages:
    - cmake
    - openssl
    - sqlite

install:
  - autotest/ci/install-build-depends.sh
script:
  - autotest/ci/build-and-test.sh

