/* THIS FILE IS AUTOMATICALLY GENERATED BY EXOTIC - DO NOT EDIT THIS FILE! */
/* exotic/0.4 (Mon Nov  7 11:15:31 CET 2011) */

#define __EXOTIC__STANDALONE__

/*
 * Exotic (EXtatic.Org Test InfrastuCture)
 * Copyright (c) 2007, Jan Vidar Krey
 */

#ifndef EXO_TEST
#define EXO_TEST(NAME, block) int exotic_test_ ## NAME (void) block
#endif

#ifndef HAVE_EXOTIC_AUTOTEST_H
#define HAVE_EXOTIC_AUTOTEST_H

#ifdef __cplusplus
extern "C" {
#endif

typedef int(*exo_test_t)();

enum exo_toggle { cfg_default, cfg_off, cfg_on };

struct exotic_handle
{
	enum exo_toggle config_show_summary;
	enum exo_toggle config_show_pass;
	enum exo_toggle config_show_fail;
	unsigned int fail;
	unsigned int pass;
	struct exo_test_data* first;
	struct exo_test_data* current;
};

extern int  exotic_initialize(struct exotic_handle* handle, int argc, char** argv);
extern void exotic_add_test(struct exotic_handle* handle, exo_test_t, const char* name);
extern int  exotic_run(struct exotic_handle* handle);

#ifdef __cplusplus
}
#endif

#endif /* HAVE_EXOTIC_AUTOTEST_H */

#include "init.tcc"
#include "test_passwd.tcc"
#include "exit.tcc"

int main(int argc, char** argv)
{
	struct exotic_handle handle;

	if (exotic_initialize(&handle, argc, argv) == -1)
		return -1;

	/* Register the tests to be run */
	exotic_add_test(&handle, &exotic_test_init_log, "init_log");
	exotic_add_test(&handle, &exotic_test_set_log_verbosity, "set_log_verbosity");
	exotic_add_test(&handle, &exotic_test_get_log_verbosity, "get_log_verbosity");
	exotic_add_test(&handle, &exotic_test_check_str_match, "check_str_match");
	exotic_add_test(&handle, &exotic_test_setup, "setup");
	exotic_add_test(&handle, &exotic_test_run_passwd, "run_passwd");
	exotic_add_test(&handle, &exotic_test_init_db, "init_db");
	exotic_add_test(&handle, &exotic_test_create_db, "create_db");
	exotic_add_test(&handle, &exotic_test_open_db_1, "open_db_1");
	exotic_add_test(&handle, &exotic_test_table_test_1, "table_test_1");
	exotic_add_test(&handle, &exotic_test_table_test_2, "table_test_2");
	exotic_add_test(&handle, &exotic_test_table_test_3, "table_test_3");
	exotic_add_test(&handle, &exotic_test_add_user_1, "add_user_1");
	exotic_add_test(&handle, &exotic_test_get_users_1, "get_users_1");
	exotic_add_test(&handle, &exotic_test_table_test_5, "table_test_5");
	exotic_add_test(&handle, &exotic_test_check_user_1, "check_user_1");
	exotic_add_test(&handle, &exotic_test_add_user_2, "add_user_2");
	exotic_add_test(&handle, &exotic_test_get_users_2, "get_users_2");
	exotic_add_test(&handle, &exotic_test_check_user_2_1, "check_user_2_1");
	exotic_add_test(&handle, &exotic_test_check_user_2_2, "check_user_2_2");
	exotic_add_test(&handle, &exotic_test_list_1, "list_1");
	exotic_add_test(&handle, &exotic_test_list_2, "list_2");
	exotic_add_test(&handle, &exotic_test_list_3, "list_3");
	exotic_add_test(&handle, &exotic_test_list_4, "list_4");
	exotic_add_test(&handle, &exotic_test_search_1, "search_1");
	exotic_add_test(&handle, &exotic_test_search_2, "search_2");
	exotic_add_test(&handle, &exotic_test_search_3, "search_3");
	exotic_add_test(&handle, &exotic_test_search_4, "search_4");
	exotic_add_test(&handle, &exotic_test_mod_user_1, "mod_user_1");
	exotic_add_test(&handle, &exotic_test_get_users_3, "get_users_3");
	exotic_add_test(&handle, &exotic_test_check_user_3_1, "check_user_3_1");
	exotic_add_test(&handle, &exotic_test_check_user_3_2, "check_user_3_2");
	exotic_add_test(&handle, &exotic_test_pass_user_1, "pass_user_1");
	exotic_add_test(&handle, &exotic_test_get_users_4, "get_users_4");
	exotic_add_test(&handle, &exotic_test_check_user_4_1, "check_user_4_1");
	exotic_add_test(&handle, &exotic_test_check_user_4_2, "check_user_4_2");
	exotic_add_test(&handle, &exotic_test_del_user_1, "del_user_1");
	exotic_add_test(&handle, &exotic_test_get_users_5, "get_users_5");
	exotic_add_test(&handle, &exotic_test_check_user_5, "check_user_5");
	exotic_add_test(&handle, &exotic_test_help_1, "help_1");
	exotic_add_test(&handle, &exotic_test_close_db_1, "close_db_1");
	exotic_add_test(&handle, &exotic_test_remove_test_db, "remove_test_db");
	exotic_add_test(&handle, &exotic_test_destroy, "destroy");
	exotic_add_test(&handle, &exotic_test_exit_log, "exit_log");

	return exotic_run(&handle);
}


/*
 * Exotic - C/C++ source code testing
 * Copyright (c) 2007, Jan Vidar Krey
 */

#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void exotic_version();

struct exo_test_data
{
	exo_test_t test;
	char* name;
	struct exo_test_data* next;
};


static void exotic_summary(struct exotic_handle* handle)
{
	int total     = handle->pass + handle->fail;
	int pass_rate = total ? (100*handle->pass / total) : 0;
	int fail_rate = total ? (100*handle->fail / total) : 0;

	printf("\n");
	printf("--------------------------------------------\n");
	printf("Results:\n");
	printf(" * Total tests run:  %8d\n", total);
	printf(" * Tests passed:     %8d (~%d%%)\n", (int) handle->pass, pass_rate);
	printf(" * Tests failed:     %8d (~%d%%)\n", (int) handle->fail, fail_rate);
	printf("--------------------------------------------\n");
}


static void exotic_help(const char* program)
{
	printf("Usage: %s [OPTIONS]\n\n", program);
	printf("Options:\n");
	printf("  --help      -h    Show this message\n");
	printf("  --version   -v    Show version\n");
	printf("  --summary   -s    show only summary)\n");
	printf("  --fail      -f    show only test failures\n");
	printf("  --pass      -p    show only test passes\n");
	printf("\nExamples:\n");
	printf("  %s -s -f\n\n", program);
}


int exotic_initialize(struct exotic_handle* handle, int argc, char** argv)
{
	int n;
	if (!handle || !argv)
		return -1;

	memset(handle, 0, sizeof(struct exotic_handle));

	for (n = 1; n < argc; n++)
	{
		if (!strcmp(argv[n], "-h") || !strcmp(argv[n], "--help"))
		{
			exotic_help(argv[0]);
			exit(0);
		}

		if (!strcmp(argv[n], "-v") || !strcmp(argv[n], "--version"))
		{
			exotic_version();
			exit(0);
		}

		if (!strcmp(argv[n], "-s") || !strcmp(argv[n], "--summary"))
		{
			handle->config_show_summary = cfg_on;
			continue;
		}

		if (!strcmp(argv[n], "-f") || !strcmp(argv[n], "--fail"))
		{
			handle->config_show_fail = cfg_on;
			continue;
		}

		if (!strcmp(argv[n], "-p") || !strcmp(argv[n], "--pass"))
		{
			handle->config_show_pass = cfg_on;
			continue;
		}

		fprintf(stderr, "Unknown argument: %s\n\n", argv[n]);
		exotic_help(argv[0]);
		exit(1);
	}

	if (handle->config_show_summary == cfg_on)
	{
		if (handle->config_show_pass == cfg_default)
			handle->config_show_pass = cfg_off;
		if (handle->config_show_fail == cfg_default)
			handle->config_show_fail = cfg_off;

	}
	else if (handle->config_show_pass == cfg_on)
	{
		if (handle->config_show_summary == cfg_default)
			handle->config_show_summary = cfg_off;
		if (handle->config_show_fail    == cfg_default)
			handle->config_show_fail = cfg_off;
	}
	else if (handle->config_show_fail == cfg_on)
	{
		if (handle->config_show_summary == cfg_default)
			handle->config_show_summary = cfg_off;
		if (handle->config_show_fail    == cfg_default)
			handle->config_show_fail = cfg_off;
	}
	else
	{
		if (handle->config_show_summary == cfg_default)
			handle->config_show_summary = cfg_on;
		if (handle->config_show_fail    == cfg_default)
			handle->config_show_fail = cfg_on;
		if (handle->config_show_pass    == cfg_default)
			handle->config_show_pass = cfg_on;
	}
	return 0;
}


void exotic_add_test(struct exotic_handle* handle, exo_test_t func, const char* name)
{
	struct exo_test_data* test;
	if (!handle)
	{
		fprintf(stderr, "exotic_add_test: failed, no handle!\n");
		exit(-1);
	}

	test = (struct exo_test_data*) malloc(sizeof(struct exo_test_data));
	if (!test)
	{
		fprintf(stderr, "exotic_add_test: out of memory!\n");
		exit(-1);
	}

	/* Create the test */
	memset(test, 0, sizeof(struct exo_test_data));
	test->test = func;
	test->name = strdup(name);

	/* Register the test in the handle */
	if (!handle->first)
	{
		handle->first = test;
		handle->current = test;
	}
	else
	{
		handle->current->next = test;
		handle->current = test;
	}
}


int exotic_run(struct exotic_handle* handle)
{
	struct exo_test_data* tmp = NULL;

	if (!handle)
	{
		fprintf(stderr, "Error: exotic is not initialized\n");
		return -1;
	}

	handle->current = handle->first;
	while (handle->current)
	{
		tmp = handle->current;

		if (handle->current->test()) {
			if (handle->config_show_pass == cfg_on)
				printf("* PASS test '%s'\n", tmp->name);
			handle->pass++;
		} else {
			if (handle->config_show_fail == cfg_on)
				printf("* FAIL test '%s'\n", tmp->name);
			handle->fail++;
		}

		handle->current = handle->current->next;

		free(tmp->name);
		free(tmp);
	}

	if (!handle->first)
	{
		printf("(No tests added)\n");
	}

	if (handle->config_show_summary == cfg_on)
		exotic_summary(handle);

	return (handle->fail) ? handle->fail : 0;
}


static void exotic_version() {
	printf("exotic 0.4-standalone\n\n");
	printf("Copyright (C) 2007 Jan Vidar Krey, janvidar@extatic.org\n");
	printf("This is free software with ABSOLUTELY NO WARRANTY.\n\n");
}
